name: CI

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: nginx
      run: |
       cd /usr/share/nginx/html
       sudo rm -rf index.html
       sudo mv /home/ec2-user/actions-runner/_work/ec2_second/ec2_second/ /usr/share/nginx/html/
