name: Jekyll site CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
       mv: /home/ec2-user/home/_work/ec2_first/ec2_first/first/ * /usr/share/nginx/html/
